name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Compile Java Files
      run: |
        javac -d "Assignment 2/out" "Assignment 2/src/LoginApp.java" "Assignment 2/src/LoginAppTest.java"  # Compile both main and test classes

    - name: Run Java Application
      run: |
        java -cp "Assignment 2/out" LoginApp  # Run the main application class

    - name: Run Tests
      run: |
        java -cp "Assignment 2/out;C:\path\to\junit-platform-console-standalone.jar" org.junit.runner.JUnitCore LoginAppTest  # Adjust path to JUnit jar if necessary
