name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Adjust based on your project's requirements

    - name: Compile Java code
      run: |
        javac -d bin src/*.java  # Adjust based on your directory structure

    - name: Run Java application
      run: |
        java -cp bin LoginApp  # Adjust based on your main class path

    # Optional: Run tests if you have them defined
    - name: Run tests
      run: |
        java -cp bin org.junit.runner.JUnitCore YourTestClassName  # Replace with your actual test class name
